Move to kotlin async with coroutines:
OleksandrKurta/Anki pull request #8
Opened 2024-08-15 13:29 UTC by Cashtan54

rewrote all project for using kotlin coroutines

2024-08-26 10:59 UTC, ajax-kovtunov-o requested changes

2024-08-26 10:59 UTC, ajax-kovtunov-o commented on src/main/kotlin/io/github/anki/anki/configuration/ThreadPoolsConfiguration.kt
> +    @Qualifier("mongo")
mongo-thread-pool

2024-08-26 21:12 UTC, ajax-kovtunov-o commented on src/main/kotlin/io/github/anki/anki/configuration/ThreadPoolsConfiguration.kt
> +            setThreadNamePrefix("Mongo-")
companion

2024-08-26 21:12 UTC, ajax-kovtunov-o commented on src/main/kotlin/io/github/anki/anki/configuration/ThreadPoolsConfiguration.kt
> +            corePoolSize = availableProcessors * 50
companion

2024-08-26 21:13 UTC, ajax-kovtunov-o commented on src/main/kotlin/io/github/anki/anki/repository/mongodb/MongoRepository.kt
> +    protected open var threadPool: ThreadPoolTaskExecutor,
why var?

2024-08-26 21:18 UTC, ajax-kovtunov-o commented on src/main/kotlin/io/github/anki/anki/configuration/ThreadPoolsConfiguration.kt
> +    fun mongoThreadPoolTaskExecutor(): ThreadPoolTaskExecutor {
return `ExecutorService`

2024-08-27 15:15 UTC, Cashtan54 commented on src/main/kotlin/io/github/anki/anki/repository/mongodb/MongoRepository.kt
> +    protected open var threadPool: ThreadPoolTaskExecutor,
fixed

2024-08-27 15:17 UTC, Cashtan54 commented on src/main/kotlin/io/github/anki/anki/configuration/ThreadPoolsConfiguration.kt
> +    fun mongoThreadPoolTaskExecutor(): ThreadPoolTaskExecutor {
fixed

2024-09-18 17:40 UTC, sashakurta approved these changes

2024-09-18 19:05 UTC, ajax-kovtunov-o approved these changes

2024-09-18 19:30 UTC, merged